raw = "data/raw"
processed = "data/processed"
input = "_chat.txt"
current = "whatsapp-20251013-212815.parq"
inputpath = "whatsapp-20251013-212815.csv"
datetime_format = "%d-%m-%Y %H:%M"
drop_authors = []