raw = "data/raw"
processed = "data/processed"
input = "_chat.txt"
current = "whatsapp-20251013-212815.parq"
preprocess_csv = "whatsapp-20251013-212815.csv"
cleaned_csv = ""
datetime_format = "%d-%m-%Y %H:%M"
drop_authors = []