raw = "data/raw"
preprocessed = "data/preprocessed"
cleaned = "data/cleaned"
processed = "data/processed"

input = "_chat.txt"
current = "whatsapp-current.parq"
preprocess_csv = ""
preprocess_parq = ""
cleaned_csv = ""
cleaned_parq = ""
feature_engineered_csv = ""
feature_engineered_parq = ""

time_series_plot_png = ""
categories_plot_png = ""
distribution_plot_png = ""
correlation_plot_png = ""
dimensionality_plot_png = ""

datetime_format = "%d-%m-%Y %H:%M"
drop_authors = []