raw = "data/raw"
preprocessed = "data/preprocessed"
cleaned = "data/cleaned"
feature_added = "data/feature_added"
processed = "data/processed"

input = "_chat.txt"
current = "whatsapp_current.parq"
preprocess_csv = "whatsapp_preprocess.csv"
preprocess_parq = "whatsapp_preprocess.parq"
cleaned_csv = "whatsapp_cleaned.csv"
cleaned_parq = "whatsapp_cleaned.parq"
feature_engineered_csv = "whatsapp_feature.csv"
feature_engineered_parq = "whatsapp_feature.parq"

time_series_plot_png = "time_series_plot.png"
categories_plot_png = "categories_plot.png"
distribution_plot_png = "distribution_plot.png"
correlation_plot_png = "correlation_plot.png"
dimensionality_plot_png = "dimensionality_plot.png"

datetime_format = "%d-%m-%Y %H:%M"
drop_authors = []