raw = "data/raw"
preprocessed = "data/preprocessed"
cleaned = "data/cleaned"
feature_added = "data/feature_added"
processed = "data/processed"

input = "_chat.txt"
current = "whatsapp-current.parq"
preprocess_csv = "whatsapp-preprocess.csv"
preprocess_parq = "whatsapp-preprocess.parq"
cleaned_csv = "whatsapp-cleaned.csv"
cleaned_parq = "whatsapp-cleaned.parq"
feature_engineered_csv = "whatsapp-feature.csv"
feature_engineered_parq = "whatsapp-feature.parq"

time_series_plot_png = ""
categories_plot_png = ""
distribution_plot_png = ""
correlation_plot_png = ""
dimensionality_plot_png = ""

datetime_format = "%d-%m-%Y %H:%M"
drop_authors = []