[directories]
raw = "data/raw"
processed = "data/processed"

input = "_chat.txt"
current = "whatsapp-20250928-214244.parq"
inputpath = "whatsapp-20250930-184920.csv"
datetime_format = "%d-%m-%Y %H:%M"
drop_authors = []
